### ISSUE TITLE
Extension is blocked by VS2019 >= 16.1 with default extension settings

### ISSUE THREAD

**Issue by kengranderson** [kyleherzog/WebDeployParametersToolkit#5]
### Installed product versions
- Visual Studio: 2019 16.3
- Web Deploy Parameters Toolkit 3.0.37

### Description
Extension is blocked by default VS2019 settings with report that the extension uses deprecated synchronous loading APIs.  

The behavior and workarounds are described here:
https://devblogs.microsoft.com/visualstudio/updates-to-synchronous-autoload-of-extensions-in-visual-studio-2019/

Changing the Visual Studio defaults as described in the page enables the extension to load.

### Steps to recreate
1. Install Extension
2. Launch VS2109 16.1 or newer
3. VS launches with yellow bar at top of screen bearing message: Visual Studio did not load one or more extensions that were using deprecated APIs.
![vs2019-1](https://user-images.githubusercontent.com/26034057/59547039-313a7080-8f06-11e9-86c9-f84388297174.jpg)

### Current behavior
Extension does not load
![vs2019-2](https://user-images.githubusercontent.com/26034057/59547041-3b5c6f00-8f06-11e9-959d-220a20b5879b.jpg)

### Expected behavior
Extension should load

**Comment by kyleherzog** [comment]
I can recreate the issue.  However, the extension was updated to load async with v3.0.37, by following this example https://github.com/microsoft/VSSDK-Extensibility-Samples/tree/master/AsyncPackageMigration 

I'm not sure why VS 2019 16.1 is still complaining.

**Comment by kengranderson** [comment]
I just downloaded the master branch and in vspackage.cs (I assume that is the right place) it looks like the sync code is still there.  Then I noticed you also have an async feature branch.

Any chance you did not finish the branch and the new build was done from master without the async feature merged in yet?

**Comment by kyleherzog** [comment]
You were right.  I hadn't fully completed the pull request.  Although, I do think v3.0.37 was a build off of the merged branches.  I went ahead and completed the pull request and ran a new build.  There is now a v3.0.38 out there.  Unfortunately, I'm still seeing the same issue though.

**Comment by kengranderson** [comment]
I'll try and see if I still get the issue.

Looking at the updated code in master, wondering if the presence of any non-async method calls or ConfigureAwait(true) vs ConfigureAwait(false) (which is claimed by some to solve all deadlocks) might be triggering the warning?

**Comment by kengranderson** [comment]
Strangely, with the updated release I not only get the warning, the plugin shows up twice?

![vsix](https://user-images.githubusercontent.com/26034057/59555371-093b2380-8f7f-11e9-9731-e5d38a3b5f4f.jpg)

**Comment by kyleherzog** [comment]
I only see it listed once on my end.

**Comment by kyleherzog** [comment]
This is fixed with version 3.1.48.
