### ISSUE TITLE
Add support for Visual Studio 2022 (version 17.*)

### ISSUE THREAD

**Issue by harris-boyce** [kyleherzog/WebDeployParametersToolkit#8]
### Installed product versions
- Visual Studio: [example 2022 Professional]

### Description
Extension does not install and is unavailable for Visual Studio 2022

### Steps to recreate
n/a

### Current behavior
Extension excludes version 17.x

### Expected behavior
Support installation for Visual Studio 2022

**Comment by kyleherzog** [comment]
Thanks for the PR.  A version 4 of the extension has just been released that includes this update.
